#!/usr/bin/env bash
# Read the root stack outputs and write them into the client/server .env files
# so local dev points at the deployed environment.
#
# Usage: outputs.sh <env>
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ENV="${1:-}"
require_env_arg "$ENV"
STACK="$(stack_name "$ENV")"

get() {
  aws cloudformation describe-stacks --stack-name "${STACK}" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

API_URL="$(get ApiUrl)"
DIST_DOMAIN="$(get WebDistributionDomain)"
USER_POOL_ID="$(get UserPoolId)"
USER_POOL_CLIENT_ID="$(get UserPoolClientId)"

CLIENT_ENV="${REPO_ROOT}/packages/client/.env"
SERVER_ENV="${REPO_ROOT}/packages/server/.env"

cat > "${CLIENT_ENV}" <<EOF
# Generated by infra/scripts/outputs.sh for env=${ENV}. Do not edit by hand.
VITE_API_URL=${API_URL}
VITE_GAME_SERVER_URL=
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
EOF

cat > "${SERVER_ENV}" <<EOF
# Generated by infra/scripts/outputs.sh for env=${ENV}. Do not edit by hand.
PORT=3001
USE_GAMELIFT=true
CLIENT_ORIGIN=https://${DIST_DOMAIN}
EOF

echo "Wrote ${CLIENT_ENV} and ${SERVER_ENV}"
