# Read the root stack outputs and write production-only client build variables.
# Local development remains configured by packages/client/.env and packages/server/.env.
#
# Usage: .\outputs.ps1 -EnvName dev
[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)][string]$EnvName
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\lib.ps1"

Assert-EnvArg $EnvName
$stack = Get-StackName $EnvName

$apiUrl = Get-StackOutput -StackName $stack -Key 'ApiUrl'
$userPoolId = Get-StackOutput -StackName $stack -Key 'UserPoolId'
$userPoolClientId = Get-StackOutput -StackName $stack -Key 'UserPoolClientId'

# Vite automatically loads this file for `vite build` but not `vite` local dev.
# An empty direct server URL intentionally selects deployed matchmaking.
$clientEnv = Join-Path $script:RepoRoot 'packages\client\.env.production'

@"
# Generated by infra/scripts/outputs.ps1 for env=$EnvName. Do not edit by hand.
VITE_API_URL=$apiUrl
VITE_GAME_SERVER_URL=
VITE_USER_POOL_ID=$userPoolId
VITE_USER_POOL_CLIENT_ID=$userPoolClientId
"@ | Set-Content -Path $clientEnv -Encoding utf8

Write-Host "Wrote $clientEnv"
