#!/usr/bin/env bash
# Read the root stack outputs and write production-only client build variables.
# Local development remains configured by packages/client/.env and packages/server/.env.
#
# Usage: outputs.sh <env>
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ENV="${1:-}"
require_env_arg "$ENV"
STACK="$(stack_name "$ENV")"

get() {
  aws cloudformation describe-stacks --stack-name "${STACK}" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

API_URL="$(get ApiUrl)"
USER_POOL_ID="$(get UserPoolId)"
USER_POOL_CLIENT_ID="$(get UserPoolClientId)"

# Vite automatically loads this file for `vite build` but not `vite` local dev.
# An empty direct server URL intentionally selects deployed matchmaking.
CLIENT_ENV="${REPO_ROOT}/packages/client/.env.production"

cat > "${CLIENT_ENV}" <<EOF
# Generated by infra/scripts/outputs.sh for env=${ENV}. Do not edit by hand.
VITE_API_URL=${API_URL}
VITE_GAME_SERVER_URL=
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
EOF

echo "Wrote ${CLIENT_ENV}"
