# Read the root stack outputs and write them into the client/server .env files
# so local dev points at the deployed environment.
#
# Usage: .\outputs.ps1 -EnvName dev
[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)][string]$EnvName
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\lib.ps1"

Assert-EnvArg $EnvName
$stack = Get-StackName $EnvName

$apiUrl = Get-StackOutput -StackName $stack -Key 'ApiUrl'
$distDomain = Get-StackOutput -StackName $stack -Key 'WebDistributionDomain'
$userPoolId = Get-StackOutput -StackName $stack -Key 'UserPoolId'
$userPoolClientId = Get-StackOutput -StackName $stack -Key 'UserPoolClientId'

$clientEnv = Join-Path $script:RepoRoot 'packages\client\.env'
$serverEnv = Join-Path $script:RepoRoot 'packages\server\.env'

@"
# Generated by infra/scripts/outputs.ps1 for env=$EnvName. Do not edit by hand.
VITE_API_URL=$apiUrl
VITE_GAME_SERVER_URL=
VITE_USER_POOL_ID=$userPoolId
VITE_USER_POOL_CLIENT_ID=$userPoolClientId
"@ | Set-Content -Path $clientEnv -Encoding utf8

@"
# Generated by infra/scripts/outputs.ps1 for env=$EnvName. Do not edit by hand.
PORT=3001
USE_GAMELIFT=true
CLIENT_ORIGIN=https://$distDomain
"@ | Set-Content -Path $serverEnv -Encoding utf8

Write-Host "Wrote $clientEnv and $serverEnv"
